export const SET_LOADING = 'SET_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';

export const GET_GLOBAL_STATS = 'GET_GLOBAL_STATS';
export const GET_GLOBAL_STATS_SUCCESS = 'GET_GLOBAL_STATS_SUCCESS';
export const GET_GLOBAL_STATS_ERROR = 'GET_GLOBAL_STATS_ERROR';

export const GET_COUNTRY_STATS = 'GET_COUNTRY_STATS';
export const GET_COUNTRY_STATS_SUCCESS = 'GET_COUNTRY_STATS_SUCCESS';
export const GET_COUNTRY_STATS_ERROR = 'GET_COUNTRY_STATS_ERROR';

export const GET_COUNTRY_CHART_STATS = 'GET_COUNTRY_CHART_STATS';
export const GET_COUNTRY_CHART_STATS_SUCCESS = 'GET_COUNTRY_CHART_STATS_SUCCESS';
export const GET_COUNTRY_CHART_STATS_ERROR = 'GET_COUNTRY_CHART_STATS_ERROR';

export const GET_NEWS_HEADLINES = 'GET_NEWS_HEADLINES';
export const GET_NEWS_HEADLINES_SUCCESS = 'GET_NEWS_HEADLINES_SUCCESS';
export const GET_NEWS_HEADLINES_ERROR = 'GET_NEWS_HEADLINES_ERROR';

export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';
